the program worked succesfully on codechef...I mainly used 3 integer arrays one for storing Alice's ratings one for bob's ratings 
and one for storing the results.The data is obtained from the user using for loops...and user a defined function compares the two
arrays and assigns points to the third array....i used a i used if-else-if to accomplish this....
....  
